"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import Navigation from "./Navigation";
import { api, clearToken } from "../lib/api";

export default function Explorer({section="dashboard"}){
 const [me,setMe]=useState(null),[data,setData]=useState(null),[schedule,setSchedule]=useState(null),[checkin,setCheckin]=useState(null),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[page,setPage]=useState(1),[loadingMore,setLoadingMore]=useState(false);
 async function load(){try{const profile=await api("me/");setMe(profile);const bundle=await api(`events/${profile.event.id}/directory/?page=1`);setData(bundle);setPage(1);setSchedule(await api("me/schedule/"));setCheckin(await api("me/check-in/"));setError("")}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function loadMore(){if(!data||loadingMore)return;setLoadingMore(true);try{const next=page+1;const bundle=await api(`events/${me.event.id}/directory/?page=${next}`);setData(current=>({...bundle,...Object.fromEntries(["employers","jobs","universities","training_providers","sessions","interview_slots","floor_maps"].map(key=>[key,[...(current?.[key]||[]),...(bundle[key]||[])]]))}));setPage(next)}catch(e){setError(e.message)}finally{setLoadingMore(false)}}
 async function action(path,method="POST",body){setBusy(true);setError("");try{await api(path,{method,body});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(error&&!me)return <main className="shell"><Navigation/><section className="card"><h1>Attendee access needed</h1><p>{error}</p><Link className="button" href="/login">Sign in</Link></section></main>;
 if(!data||!me)return <main className="shell"><Navigation/><p>Loading your event…</p></main>;
 const event=data.event;
 const employerCards=<div className="grid">{data.employers.map(e=><article className="card" key={e.id}>{e.logo_url&&<img src={e.logo_url} alt="" width="64"/>}<h3>{e.name}</h3><p>{e.description}</p>{e.booth&&<span className="badge">Booth {e.booth.number} · {e.booth.name}</span>}{e.website&&<p><a href={e.website}>Employer website ↗</a></p>}</article>)}</div>;
 const jobs=<div className="grid">{data.jobs.map(j=><article className="card" key={j.id}><span className="badge">{j.employment_type.replaceAll("_"," ")}</span><h3>{j.title}</h3><p className="muted">{j.employer} · {j.location} · {j.experience_level}</p><p>{j.description}</p><p className="muted">{j.requirements}</p><button className="secondary" disabled={busy||me.approval_status!=="approved"} onClick={()=>action(`jobs/${j.id}/bookmark/`,j.saved?"DELETE":"POST")}>{j.saved?"Saved · remove":"Save job"}</button> {j.application_url&&<a className="button" href={j.application_url} target="_blank" rel="noreferrer">Apply ↗</a>} {!j.application_url&&j.application_email&&<a className="button" href={`mailto:${j.application_email}`}>Email to apply</a>}</article>)}</div>;
 const universities=<div className="grid">{data.universities.map(u=><article className="card" key={u.id}><h3>{u.name}</h3><p>{u.description}</p>{u.website&&<a href={u.website}>Website ↗</a>}{u.programs.map(p=><div className="card" key={p.id}><h4>{p.name}</h4><p>{p.description}</p><p className="muted">{p.eligibility}</p><p>{p.upcoming_batch_info} {p.internship_fresher_info}</p></div>)}</article>)}</div>;
 const training=<div className="grid">{data.training_providers.map(p=><article className="card" key={p.id}><h3>{p.name}</h3><p>{p.description}</p>{p.promotions.map(v=><div className="card" key={v.id}><span className="badge">{v.value||"Promotion"}</span><h4>{v.title}</h4><p>{v.description}</p>{v.expires_at&&<p className="muted">Until {new Date(v.expires_at).toLocaleDateString()}</p>}{v.document_url&&<p><a href={v.document_url}>Promotion details ↗</a></p>}<button disabled={busy||me.approval_status!=="approved"} onClick={()=>action(`promotions/${v.id}/claim/`)}>Claim promotion</button></div>)}</article>)}</div>;
 const sessions=<div className="grid">{data.sessions.map(s=><article className="card" key={s.id}><span className="badge">{s.remaining===null?"Open":`${s.remaining} places`}</span><h3>{s.title}</h3><p>{new Date(`${s.date}T00:00:00`).toLocaleDateString()} · {s.start_time.slice(0,5)}–{s.end_time.slice(0,5)}</p><p>{s.location} · {s.speaker}</p><p>{s.description}</p><button disabled={busy||me.approval_status!=="approved"||s.remaining===0} onClick={()=>action(`sessions/${s.id}/registration/`)}>Add to my schedule</button></article>)}</div>;
 const interviews=<div className="grid">{data.interview_slots.map(slot=><article className="card" key={slot.id}><h3>{slot.employer}</h3><p>{new Date(`${slot.date}T00:00:00`).toLocaleDateString()} · {slot.start_time.slice(0,5)}–{slot.end_time.slice(0,5)}</p><p className="muted">{slot.interviewer_info}</p><div className="stack">{slot.options.map(option=><button key={option.start_time} disabled={busy||me.approval_status!=="approved"||!option.remaining} onClick={()=>action(`interview-slots/${slot.id}/booking/`,"POST",{start_time:option.start_time})}>{option.start_time} · {option.remaining} places</button>)}</div></article>)}</div>;
 const map=<div className="stack"><label>Find a booth<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, organization, category or booth number"/></label>{data.floor_maps.map(m=>{const booths=m.booths.filter(b=>`${b.number} ${b.name} ${b.organization_name} ${b.category}`.toLowerCase().includes(search.toLowerCase()));return <article className="card" key={m.id}><h3>{m.name} {m.version&&<small className="muted">· {m.version}</small>}</h3><p>{m.description}</p><div className="boothmap"><img src={m.image_url} alt={`${m.name} event map`}/>{booths.map(b=><div key={b.id} className="booth-pin" title={`${b.number} ${b.name}`} style={{left:`${b.x_percent}%`,top:`${b.y_percent}%`,width:`${b.width_percent}%`,height:`${b.height_percent}%`}}>{b.number}</div>)}</div><div className="grid">{booths.map(b=><div className="card" key={b.id}><b>{b.number} · {b.name}</b><p>{b.organization_name||b.category}</p><p className="muted">{b.description}</p></div>)}</div></article>})}</div>;
 let title="Your attendee dashboard",content=<div className="grid"><article className="card"><h2>Welcome, {me.name}</h2><p className="muted">{event.title} · {event.venue}</p><span className="badge">Registration {me.approval_status}</span><p>{event.description}</p><p>{new Date(event.start_date).toLocaleDateString()} · {event.event_time}</p></article><article className="card"><h2>My schedule</h2><p>{schedule ? `${schedule.interviews.length} interviews · ${schedule.sessions.length} sessions` : "Loading your schedule…"}</p><Link className="button secondary" href="/dashboard/bookings">View schedule</Link></article></div>;
 if(section==="employers"){title="Employers";content=employerCards}if(section==="jobs"){title="Jobs";content=jobs}if(section==="universities"){title="Universities & programs";content=universities}if(section==="training-providers"){title="Training & promotions";content=training}if(section==="sessions"||section==="dashboard/sessions"){title="Event sessions";content=sessions}if(section==="floor-map"){title="Floor maps & booths";content=map}
 if(section==="interviews"){title="Interview availability";content=interviews}
 if(section==="dashboard/bookings"){title="My schedule & saved items";content=<div className="grid"><article className="card"><h2>Sessions</h2>{schedule?.sessions?.map(s=><p key={s.id}>{s.title} · {s.date} {s.start_time} <button className="secondary" onClick={()=>action(`sessions/${s.id}/registration/`,"DELETE")}>Cancel</button></p>)}</article><article className="card"><h2>Interviews</h2>{schedule?.interviews?.map(b=><p key={b.booking_id}>{b.employer} · {b.date} {b.start_time} <button className="secondary" onClick={()=>action(`interview-slots/${b.slot_id}/booking/`,"DELETE")}>Cancel</button></p>)}</article><article className="card"><h2>Saved jobs</h2>{schedule?.saved_jobs?.map(j=><p key={j.id}>{j.title} · {j.employer}</p>)}</article><article className="card"><h2>Promotions</h2>{schedule?.promotions?.map(v=><p key={v.claim_id}>{v.title} · {v.provider} <button className="secondary" onClick={()=>action(`promotions/${v.promotion_id}/claim/`,"DELETE")}>Cancel claim</button></p>)}</article></div>}
 if(section==="check-in"){title="Check-in";content=<article className="card"><h2>{checkin?.registration_number||"Registration pending"}</h2><p>Approval: {checkin?.approval_status}</p><p>Check-in status: {checkin?.checked_in?"Checked in":"Not checked in yet"}</p>{checkin?.qr_code?<><img src={checkin.qr_code} width="220" height="220" alt="Your event check-in QR code"/><p className="muted">Show this QR code to the event team at check-in.</p></>:<p className="muted">Your check-in QR code will appear here after your registration is approved.</p>}</article>}
 return <main className="shell"><Navigation/><div className="eyebrow muted">{event.title}</div><div className="section-title"><div><h1>{title}</h1><p className="muted">{me.approval_status!=="approved"?"Your registration is waiting for event team approval. Booking features become available after approval.":"Explore and manage your event activities."}</p></div><button className="secondary" onClick={()=>{clearToken();location.href="/login"}}>Sign out</button></div>{error&&<p className="error">{error}</p>}{content}{Object.values(data.pagination?.has_more||{}).some(Boolean)&&<div className="center"><button className="secondary" disabled={loadingMore} onClick={loadMore}>{loadingMore?"Loading…":"Load more"}</button></div>}</main>;
}
