# Generated by Django 5.2.1 on 2025-05-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeration',
            new_name='Registration',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fk_reg',
        ),
        migrations.AddField(
            model_name='player',
            name='fkregistration',
            field=models.ForeignKey(db_column='fkRegistration', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='register.registration'),
        ),
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(blank=True, db_column='designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='handicap',
            field=models.CharField(blank=True, db_column='handicap', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(blank=True, db_column='mobile', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='organization',
            field=models.CharField(blank=True, db_column='organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], db_column='tsize', max_length=5),
        ),
    ]
