# Generated by Django 5.2.1 on 2025-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_registeration_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(blank=True, db_column='designation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='handicap',
            field=models.CharField(blank=True, db_column='handicap', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Sir', 'Sir'), ('Madam', 'Madam')], max_length=10, null=True),
        ),
    ]
