# Generated by Django 5.2 on 2025-05-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_player_designation_alter_player_handicap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_no', models.CharField(max_length=20, unique=True)),
                ('package_name', models.CharField(max_length=100)),
                ('package_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Sir', 'Sir'), ('Madam', 'Madam')], max_length=10)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('billing_organization', models.CharField(max_length=100)),
                ('billing_name', models.CharField(max_length=100)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_designation', models.CharField(max_length=100)),
                ('billing_address', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('fksponsorpackage', models.ForeignKey(db_column='fksponsorpackage', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='register.sponsorpackage')),
            ],
        ),
    ]
