# Generated by Django 5.2 on 2025-05-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_sponsorpackage_sponsorship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='fksponsorpackage',
        ),
        migrations.DeleteModel(
            name='SponsorPackage',
        ),
    ]
