# Generated by Django 5.2 on 2025-05-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_sponsorship_fksponsorpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='package',
            field=models.CharField(choices=[('P1', 'GOLD SPONSOR (RM 30,000)'), ('P2', 'DUFFLE BAG SPONSOR (RM 25,000)'), ('P3', 'GOLF CAP SPONSOR (RM 15,000)'), ('P4', 'UMBRELLASPONSOR (RM 15,000)'), ('P5', 'GOLF SLEEVE SPONSO (RM 10,000)'), ('P6', 'TEE-BOX & NOVELTY SPONSORS (RM 3,500 / Each)'), ('P7', 'GOLF GALA DINNER SPONSOR (RM 25,000)'), ('P8', 'LUNCHEON SPONSOR (RM 10,000)'), ('P9', 'GOLF GALA DINNER TABLE SPONSOR (RM 2,500)'), ('P10', 'GOLF FLIGHT SPONSOR (RM 4,000)'), ('P11', '2 GOLFERS SPONSOR (RM 2,200)')], db_column='package', default=None, max_length=10),
        ),
    ]
