# Generated by Django 5.2 on 2025-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_sponsorship_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
