# Generated by Django 5.2 on 2025-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_sponsorship_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='package',
            field=models.CharField(choices=[('P1', 'PLATINUM SPONSOR (RM 50,000)'), ('P2', 'GOLD SPONSOR (RM 35,000)'), ('P3', 'GOLF T-SHIRT SPONSOR (RM 30,000)'), ('P4', 'DUFFLE BAG SPONSOR (RM 25,000)'), ('P5', 'GOLF CAP SPONSOR (RM 15,000)'), ('P6', 'UMBRELLA SPONSOR (RM 15,000)'), ('P7', 'GOLF SLEEVE SPONSOR (RM 10,000)'), ('P8', 'TEE-BOX & NOVELTY SPONSOR (RM 3,500 EACH)'), ('P9', 'GOLF GALA DINNER SPONSOR (RM 25,000)'), ('P10', 'LUNCHEON SPONSOR (RM 10,000)'), ('P11', 'GOLF GALA DINNER TABLE SPONSOR (RM 2,500)'), ('P12', 'GOLF FLIGHT SPONSOR (RM 4,000)'), ('P13', 'GOLF BALLS SPONSOR (RM 10,000)')], db_column='package', default=None, max_length=10),
        ),
    ]
