# Generated by Django 5.2.1 on 2025-05-28 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_sponsorship_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='qr_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='registration_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
