# Generated by Django 5.2 on 2025-06-03 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('registration_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('qr_sent', models.BooleanField(default=False)),
                ('campaign_code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
