# Generated by Django 5.2 on 2025-06-03 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_submission_campaign_campaign_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='created_on',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
