# Generated by Django 5.2 on 2025-06-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_rename_created_on_submission_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='comp_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
