# Generated by Django 5.2 on 2025-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_registration_address_registration_comp_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='billing_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='billing_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
