# Generated by Django 5.2 on 2025-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_sponsorship_billing_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='campaign_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='campaign_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='campaign_code',
            field=models.CharField(max_length=255),
        ),
    ]
