# Generated by Django 5.2 on 2025-06-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_registration_campaign_code_sponsorship_campaign_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='comp_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
