# Generated by Django 5.2 on 2025-06-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_registration_comp_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='billing_reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
