# Generated by Django 5.2 on 2025-06-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_alter_sponsorship_billing_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
