# Generated by Django 5.2 on 2025-06-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_player_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='need_qr',
            field=models.BooleanField(default=False),
        ),
    ]
