# Generated by Django 5.2 on 2025-06-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_campaign_need_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pic_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
