# Generated by Django 5.2 on 2025-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_campaign_pic_email_alter_submission_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='submitted_by_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='submitted_by_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
