# Generated by Django 5.2 on 2025-08-28 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_registration_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='entry_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='entry_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='fk_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.campaign'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='member_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='handicap',
            field=models.CharField(blank=True, db_column='handicap', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(blank=True, db_column='mobile', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Sir', 'Sir'), ('Madam', 'Madam')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='comp_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='submitted_by_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='billing_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='billing_reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='package',
            field=models.CharField(choices=[('P1', 'PLATINUM SPONSOR (RM 50,000)'), ('P2', 'GOLD SPONSOR (RM 35,000)'), ('P3', 'GOLF T-SHIRT SPONSOR (RM 30,000)'), ('P4', 'DUFFLE BAG SPONSOR (RM 25,000)'), ('P5', 'GOLF CAP SPONSOR (RM 15,000)'), ('P6', 'UMBRELLA SPONSOR (RM 15,000)'), ('P7', 'GOLF SLEEVE SPONSOR (RM 10,000)'), ('P8', 'TEE-BOX & NOVELTY SPONSOR (RM 3,500 EACH)'), ('P9', 'GOLF GALA DINNER SPONSOR (RM 25,000)'), ('P10', 'LUNCHEON SPONSOR (RM 10,000)'), ('P11', 'GOLF GALA DINNER TABLE SPONSOR (RM 2,500)'), ('P12', 'GOLF FLIGHT SPONSOR (RM 4,000)'), ('P13', 'GOLF BALLS SPONSOR (RM 10,000)')], db_column='package', default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='reg_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='submitted_by_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reg_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
