# Generated by Django 5.2 on 2025-08-28 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_campaign_entry_keyword_campaign_entry_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='fk_campaign',
        ),
        migrations.AddField(
            model_name='submission',
            name='fkcampaign',
            field=models.ForeignKey(blank=True, db_column='fkcampaign', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='register.campaign'),
        ),
    ]
