# Generated by Django 5.2 on 2025-08-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_team_alter_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_team', to='register.team'),
        ),
    ]
