# Generated by Django 5.2 on 2025-08-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_campaign_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
