# Generated by Django 5.2 on 2025-08-29 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_remove_campaign_team_delete_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_teams', to='register.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
