# Generated by Django 5.2 on 2025-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_survey_end_date_survey_is_active_survey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
