# Generated by Django 5.2 on 2025-09-09 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_question_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
