# Generated by Django 5.2 on 2025-10-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0035_alter_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='promo_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
