# Generated by Django 5.2 on 2025-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_submission_category_submission_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
