# Generated by Django 5.2 on 2025-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0037_submission_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='exclude_columns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
