# Generated by Django 5.2.4 on 2025-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0038_campaign_exclude_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='prompt_checkin_info',
            field=models.BooleanField(default=True),
        ),
    ]
