# Generated by Django 5.2.5 on 2026-05-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0038_surveyuser_checkin_fields'),
        ('register', '0039_campaign_prompt_checkin_info'),
    ]

    operations = [
    ]
