# Generated by Django 5.2.5 on 2026-05-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_survey_purpose'),
        ('register', '0040_merge_20260525_0428'),
    ]

    operations = [
    ]
