# Generated by Django 5.2.5 on 2026-05-25 08:21

import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0041_merge_0039_survey_purpose_0040_merge_20260525_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='form_banners/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='identity_field_config',
            field=models.JSONField(default=register.models.default_identity_field_config),
        ),
    ]
