# Generated by Django 5.2.5 on 2026-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0044_seed_identity_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_followups',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
