# Generated by Django 5.2.5 on 2026-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0045_question_choice_followups'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_in_list',
            field=models.BooleanField(default=False, help_text="If True, this question's answer is shown as a column in the registrations list."),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='qr_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='reg_no',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
