# Generated by Django 5.2.5 on 2026-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0047_backfill_surveyuser_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='list_column_label',
            field=models.CharField(blank=True, help_text='Optional short label used as the column header in the registrations list. Falls back to a truncated question text when empty.', max_length=60),
        ),
    ]
