# Generated by Django 5.2.5 on 2026-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0048_question_list_column_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, help_text="Human-friendly identifier used in the public URL (e.g. 'cio-conference-2026'). Auto-generated from the title.", max_length=80, null=True, unique=True),
        ),
    ]
