# Generated by Django 5.2.4 on 2026-07-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0066_surveyuser_participant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Open Text'), ('textarea', 'Paragraph'), ('radio', 'Single Choice'), ('checkbox', 'Multiple Choice'), ('select', 'Dropdown'), ('matrix_roles', 'Roles & Skills Matrix (Section C - Q6)'), ('identity_name', 'Identity — Name'), ('identity_participant_type', 'Identity — Participant Type'), ('identity_email', 'Identity — Email'), ('identity_phone', 'Identity — Phone'), ('identity_organization', 'Identity — Organization')], default='text', max_length=32),
        ),
    ]
