# Generated by Django 5.2.4 on 2026-10-06 22:41

import django.db.models.deletion
import register.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0070_phase3_career_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic_email', models.TextField(blank=True, default='')),
                ('event_time', models.CharField(blank=True, default='', max_length=120)),
                ('venue', models.TextField(blank=True, default='')),
                ('dress_code', models.CharField(blank=True, default='', max_length=120)),
                ('extra_info', models.JSONField(blank=True, default=register.models.default_golf_extra_info)),
                ('confirmation_subject', models.CharField(blank=True, default='', max_length=200)),
                ('confirmation_intro', models.TextField(blank=True, default='')),
                ('show_banner_confirmation', models.BooleanField(default=True)),
                ('show_details_confirmation', models.BooleanField(default=True)),
                ('email_signoff', models.TextField(blank=True, default='')),
                ('registration_closed_intro', models.TextField(blank=True, default='')),
                ('theme_color', models.CharField(blank=True, default='#198754', max_length=7)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GolfForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kind', models.CharField(choices=[('participant', 'Participant Form'), ('sponsor', 'Sponsor Form')], default='participant', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text="Human-friendly identifier used in the public URL (e.g. 'pikom-golf-2026'). Auto-generated from the title.", max_length=80, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='golf_banners/')),
                ('show_event_details', models.BooleanField(default=False, help_text="Show the event's details block (date, time, venue, etc.) at the top of the public page.")),
                ('note', models.TextField(blank=True, default='')),
                ('player_slots', models.PositiveSmallIntegerField(default=4, help_text='How many player sub-forms to show (a flight is 4).')),
                ('required_players', models.PositiveSmallIntegerField(default=4, help_text='How many of those player sub-forms must be completed.')),
                ('package_label', models.CharField(blank=True, default='Participation Package', help_text='Label shown next to the base package price.', max_length=200)),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, help_text='One base price for the whole entry (covers all player slots).', max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='RM', max_length=8)),
                ('player_field_config', models.JSONField(default=register.models.default_golf_player_field_config)),
                ('salutation_options', models.JSONField(default=register.models.default_golf_salutations)),
                ('tshirt_sizes', models.JSONField(default=register.models.default_golf_tshirt_sizes)),
                ('size_guide_label', models.CharField(blank=True, default='Size guide', help_text='Text of the link shown next to the T-shirt size field on the public page. The link only appears once size images exist.', max_length=80)),
                ('fkevent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='register.golfevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GolfQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Display order on the form.')),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Open Text'), ('textarea', 'Paragraph'), ('radio', 'Single Choice'), ('checkbox', 'Multiple Choice'), ('select', 'Dropdown')], default='text', max_length=32)),
                ('choices', models.JSONField(blank=True, help_text='Options for radio/checkbox/select.', null=True)),
                ('allow_other', models.BooleanField(default=False, help_text="Include an 'Other' free-text input.")),
                ('max_checks', models.PositiveIntegerField(blank=True, help_text='Optional limit for checkbox selections.', null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('show_in_list', models.BooleanField(default=False, help_text='If True, this answer is shown as a column in the entries list.')),
                ('list_column_label', models.CharField(blank=True, help_text='Optional short column header for the entries list.', max_length=60)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='register.golfform')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GolfRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('registration_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('contact_designation', models.CharField(blank=True, default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_company', models.CharField(blank=True, default='', max_length=255)),
                ('billing_reg_no', models.CharField(blank=True, default='', max_length=100)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('billing_designation', models.CharField(blank=True, default='', max_length=255)),
                ('billing_contact_number', models.CharField(blank=True, default='', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, default='RM', max_length=8)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Organiser review state of this entry.', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='golf_registration_approvals', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='register.golfform')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GolfAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('selected_options', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='register.golfform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='register.golfquestion')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='register.golfregistration')),
            ],
        ),
        migrations.CreateModel(
            name='GolfSizeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='golf_size_images/')),
                ('caption', models.CharField(blank=True, default='', help_text='Optional line shown under the slide.', max_length=200)),
                ('number', models.PositiveIntegerField(default=0, help_text='Slide order.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_images', to='register.golfform')),
            ],
            options={
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GolfSponsorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, help_text='Display order on the sponsor page.')),
                ('image', models.ImageField(blank=True, help_text='The package image — the main picture on the item card.', null=True, upload_to='golf_sponsor_items/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='The item price. This is the only price shown on the sponsor page, and the amount a sponsor is charged for it.', max_digits=12)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='The participant add-on price — shown ONLY on the participant page, never on the sponsor page. Mandatory when `show_in_participant` is set. May be higher or lower than `price`.', max_digits=12, null=True)),
                ('description', models.TextField(blank=True, help_text='Rich text shown on the item card.')),
                ('logo', models.ImageField(blank=True, help_text="Optional. The logo of the sponsor who BOUGHT this item, uploaded by an organiser. Shown on the top-right corner of the card once the item is sold out; when absent the card shows 'NOT AVAILABLE' instead. Not displayed while the item is still available.", null=True, upload_to='golf_sponsor_logos/')),
                ('once_only', models.BooleanField(default=False, help_text="Item can only be taken once. After the first entry the card becomes unclickable and credits the buyer's logo (or shows 'TAKEN').")),
                ('show_in_participant', models.BooleanField(default=False, help_text='Also offer this item as a paid add-on on the participant form.')),
                ('is_available', models.BooleanField(default=True, help_text="Organiser switch for whether this item can still be taken. Turn it off to close the item by hand (e.g. sold offline): it stays listed but the card becomes unclickable and shows the buyer's logo — or 'TAKEN' when no logo is set. Independent of `once_only`, which closes the item automatically after the first entry.")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the item appears on the public page at all.')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_items', to='register.golfform')),
            ],
            options={
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GolfSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_addon', models.BooleanField(default=False, help_text='True when picked as an add-on on the participant form.')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='register.golfregistration')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='register.golfsponsoritem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GolfEventTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teams', to='register.golfevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_event_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GolfPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(default=1, help_text='Player 1..4 within the entry.')),
                ('salutation', models.CharField(blank=True, default='', max_length=50)),
                ('salutation_other', models.CharField(blank=True, default='', help_text="Free text captured when the salutation is 'Others'.", max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('handicap', models.CharField(blank=True, default='', help_text='USGA handicap.', max_length=50)),
                ('is_tgcc_member', models.BooleanField(default=False)),
                ('tgcc_membership_no', models.CharField(blank=True, default='', max_length=100)),
                ('organisation', models.CharField(blank=True, default='', max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('mobile', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tshirt_size', models.CharField(blank=True, default='', max_length=10)),
                ('registration_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='register.golfregistration')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('registration', 'slot')},
            },
        ),
    ]
