# Generated by Django 5.2 on 2025-08-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
