# Generated by Django 5.2 on 2025-08-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
